FROM nginx
COPY ./dist/  /usr/share/nginx/html/
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./identity.isawesome.cn.crt /etc/nginx/identity.isawesome.cn.crt
COPY ./identity.isawesome.cn.key /etc/nginx/identity.isawesome.cn.key
